swssconfig/sample/netbouncer.json etc/swss/config.d
swssconfig/sample/00-copp.config.json etc/swss/config.d
swssconfig/sample/msn2700.32ports.buffers.json etc/swss/config.d
swssconfig/sample/msn2700.32ports.qos.json etc/swss/config.d
swssconfig/sample/msn2740.32ports.buffers.json etc/swss/config.d
swssconfig/sample/msn2740.32ports.qos.json etc/swss/config.d
swssconfig/sample/td2.32ports.buffers.json etc/swss/config.d
swssconfig/sample/td2.32ports.qos.json etc/swss/config.d
